# AI
langchain4j:
  open-ai:
    chat-model:
      base-url: https://api.deepseek.com
      api-key: REDACTED_API_KEY
      model-name: deepseek-chat
      max-tokens: 8192
      log-requests: true
      log-responses: true
      strict-json-schema: true
      response-format: json_object
